#:schema node_modules/wrangler/config-schema.json
name = "yogurt-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true

[ai]
binding = "AI"
